from typing import Any, Awaitable, Callable, ParamSpec, TypeVar

P = ParamSpec("P")
T = TypeVar("T")
Injected: Any

def injectable(func: Callable[P, Awaitable[T]]) -> Callable[P, Awaitable[T]]: ...
def injectable_sync(func: Callable[P, T]) -> Callable[P, T]: ...
def add_injectable(annotation: Any, injectable: Any) -> None: ...
